export const JOB_TAGS: string[] = [
    // Frontend
    "React",
    "Next.js",
    "Vue.js",
    "Angular",
    "Svelte",
    "TypeScript",
    "JavaScript",
    "HTML",
    "CSS",
    "Tailwind CSS",
    "Bootstrap",
    "SASS/SCSS",
    "Redux",
    "Zustand",
    "React Query",
    "GraphQL",
    "REST API",
    "Webpack",
    "Vite",

    // Backend
    "Node.js",
    "Express.js",
    "NestJS",
    "Django",
    "FastAPI",
    "Flask",
    "Laravel",
    "Spring Boot",
    "ASP.NET",
    ".NET Core",
    "Ruby on Rails",
    "Go (Golang)",
    "Rust",
    "PHP",
    "Python",
    "Java",
    "C#",
    "C++",
    "Kotlin",

    // Mobile
    "iOS",
    "Android",
    "Swift",
    "SwiftUI",
    "React Native",
    "Flutter",
    "Dart",

    // Database
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "SQLite",
    "Cassandra",
    "DynamoDB",
    "Elasticsearch",
    "Prisma",
    "TypeORM",
    "Sequelize",

    // DevOps & Cloud
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "GCP",
    "CI/CD",
    "Jenkins",
    "GitHub Actions",
    "Terraform",
    "Ansible",
    "Linux",
    "Nginx",
    "Apache",
    "Serverless",

    // AI / ML / Data
    "Machine Learning",
    "Deep Learning",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "NLP",
    "Computer Vision",
    "Data Science",
    "Data Engineering",
    "Data Analysis",
    "Power BI",
    "Tableau",
    "Pandas",
    "NumPy",
    "Spark",
    "Hadoop",
    "ETL",

    // Design
    "UI Design",
    "UX Design",
    "Figma",
    "Adobe XD",
    "Sketch",
    "Photoshop",
    "Illustrator",
    "User Research",
    "Wireframing",
    "Prototyping",
    "Motion Design",

    // Project & Product
    "Product Management",
    "Project Management",
    "Agile",
    "Scrum",
    "Kanban",
    "JIRA",
    "Confluence",
    "Roadmapping",
    "OKRs",

    // QA
    "QA Engineering",
    "Manual Testing",
    "Automated Testing",
    "Selenium",
    "Cypress",
    "Jest",
    "Playwright",
    "Test Driven Development",

    // Security
    "Cybersecurity",
    "Penetration Testing",
    "Network Security",
    "OWASP",

    // Business / Finance
    "Accounting",
    "Financial Analysis",
    "Bookkeeping",
    "Taxation",
    "Auditing",
    "Budget Management",

    // Marketing
    "Digital Marketing",
    "SEO",
    "SEM",
    "Google Ads",
    "Social Media Marketing",
    "Content Marketing",
    "Email Marketing",
    "Copywriting",
    "Brand Strategy",
    "Growth Hacking",
    "CRO",
    "Analytics",

    // Sales & Support
    "Sales",
    "Business Development",
    "Account Management",
    "CRM",
    "Customer Support",
    "Customer Success",

    // HR & Operations
    "HR Management",
    "Recruitment",
    "Talent Acquisition",
    "Payroll",
    "Operations Management",
    "Supply Chain",
    "Logistics",

    // Legal
    "Legal Research",
    "Contract Management",
    "Compliance",

    // Communication
    "Technical Writing",
    "Documentation",
    "Public Relations",

    // Soft skills
    "Leadership",
    "Team Management",
    "Communication",
    "Problem Solving",
    "Critical Thinking",

    // Miscellaneous
    "Open Source",
    "Microservices",
    "API Development",
    "WebSocket",
    "gRPC",
    "Blockchain",
    "Web3",
    "Smart Contracts",
    "Solidity",
];
